import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import type { AppConfig } from '../config.js';
import type { ProjectFileInput } from '../compile/runner.js';

/**
 * Builds the command that executes a project's Python and the host paths the run
 * reads/writes. In `docker` mode (default) each run is a fresh `docker run --rm`
 * from the pyrun image — non-root, resource/time-limited, network off by default,
 * with the project source mounted READ-ONLY and only `figures/` + the run's
 * `.pyout/<runId>/` scratch writable. In `local` mode it spawns host `python3`
 * directly (DEV/TEST ONLY, not sandboxed — see ADR-013).
 */

export interface RunPlanInput {
  projectId: string;
  runId: string;
  /** Project-relative path of the .py to run. */
  scriptPath: string;
  args: string[];
  networkEnabled: boolean;
}

export interface RunPlan {
  command: string;
  argv: string[];
  cwd?: string;
  /** Extra env for the child (local mode; the docker path passes env via `-e`). */
  env?: Record<string, string>;
  killGroup: boolean;
  /** docker container name to `docker kill` on stop (null in local mode). */
  containerName: string | null;
}

/**
 * Wrapper run as `__main__`'s launcher so the ubiquitous `plt.show()` idiom
 * actually produces output: under the headless Agg backend `show()` is a no-op,
 * so a script that plots and shows would otherwise write nothing. This shim makes
 * `plt.show()` — and any figures still open when the script ends — save into
 * PYRUN_OUTDIR (the run's scratch dir, surfaced in the output window) as BOTH a
 * vector `.pdf` (the file you add to the document, for LaTeX-quality figures) and
 * a `.png` thumbnail (for the preview strip). Explicit `savefig('figures/…')`
 * still writes a durable, imported project figure in whatever format you choose.
 */
export const BOOTSTRAP_NAME = '_pyrun_main.py';
const PYRUN_BOOTSTRAP = `# Auto-generated by the LaTeX Studio Python "Run" sandbox — do not edit.
import os, sys, runpy

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
except Exception:
    plt = None

_OUT = os.environ.get("PYRUN_OUTDIR", ".")
_MAX = 50
_seq = [0]

def _capture():
    if plt is None:
        return
    for num in plt.get_fignums():
        if _seq[0] >= _MAX:
            break
        _seq[0] += 1
        fig = plt.figure(num)
        stem = os.path.join(_OUT, "figure_%02d" % _seq[0])
        # Vector PDF (added to the document) + raster PNG (thumbnail preview).
        for ext, kw in ((".pdf", {}), (".png", {"dpi": 150})):
            try:
                fig.savefig(stem + ext, bbox_inches="tight", **kw)
            except Exception as exc:
                sys.stderr.write("[pyrun] figure capture failed (%s): %s\\n" % (ext, exc))

if plt is not None:
    def _show(*args, **kwargs):
        _capture()
        plt.close("all")
    plt.show = _show  # make the standard plt.show() idiom visible in the output

_script = sys.argv[1]
sys.argv = sys.argv[1:]  # the user script sees argv as if invoked directly
_dir = os.path.dirname(os.path.abspath(_script)) or os.getcwd()
if _dir not in sys.path:
    sys.path.insert(0, _dir)  # let the script import its sibling modules
try:
    runpy.run_path(_script, run_name="__main__")
finally:
    _capture()  # also save figures left open without an explicit show()
`;

/** Write the run launcher into the run's scratch dir (mounted at /pyout). */
export async function writeBootstrap(config: AppConfig, projectId: string, runId: string): Promise<void> {
  await writeFile(join(pyoutDir(config, projectId, runId), BOOTSTRAP_NAME), PYRUN_BOOTSTRAP, 'utf8');
}

/** Host dir holding the project's staged files (shared with compile). */
export function projectDir(config: AppConfig, projectId: string): string {
  return join(config.compileWorkspace, projectId);
}

export function figuresDir(config: AppConfig, projectId: string): string {
  return join(projectDir(config, projectId), 'figures');
}

export function pyoutDir(config: AppConfig, projectId: string, runId: string): string {
  return join(projectDir(config, projectId), '.pyout', runId);
}

/** Stage the project's DB files onto the workspace (same layout compile uses). */
export async function stageFiles(config: AppConfig, projectId: string, files: ProjectFileInput[]): Promise<void> {
  const dir = projectDir(config, projectId);
  await mkdir(dir, { recursive: true });
  for (const f of files) {
    const dest = join(dir, f.path);
    await mkdir(dirname(dest), { recursive: true });
    await writeFile(dest, Buffer.from(f.content, f.encoding === 'base64' ? 'base64' : 'utf8'));
  }
}

export function buildRunPlan(config: AppConfig, input: RunPlanInput): RunPlan {
  const { projectId, runId, scriptPath, args, networkEnabled } = input;

  if (config.pyrunMode === 'local') {
    // Not sandboxed. Timeout + group-kill are enforced host-side by the manager.
    const bootstrap = join(pyoutDir(config, projectId, runId), BOOTSTRAP_NAME);
    return {
      command: 'python3',
      argv: [bootstrap, scriptPath, ...args],
      cwd: projectDir(config, projectId),
      env: { MPLBACKEND: 'Agg', PYTHONUNBUFFERED: '1', PYRUN_OUTDIR: pyoutDir(config, projectId, runId) },
      killGroup: true,
      containerName: null,
    };
  }

  // docker: in-container `timeout` is a backstop (longer than the host timer, the
  // authoritative one). The whole container is killed by name on stop/supersede.
  const backstopSecs = Math.ceil(config.pyrunTimeoutMs / 1000) + 10;
  const inner = ['timeout', '-s', 'KILL', String(backstopSecs), 'python', `/pyout/${BOOTSTRAP_NAME}`, scriptPath, ...args]
    .map(shellQuote)
    .join(' ');
  const projHost = join(config.pyrunWorkspaceHost, projectId);
  const containerName = `pyrun-${projectId}-${runId}`;
  const argv = [
    'run',
    '--rm',
    '--name',
    containerName,
    // gVisor (runsc) when configured: a user-space kernel intercepts syscalls, so
    // a hostile script never reaches the host kernel directly. Empty ⇒ daemon
    // default (runc). See docs/isolation.md.
    ...(config.pyrunRuntime ? ['--runtime', config.pyrunRuntime] : []),
    '--network',
    networkEnabled ? 'bridge' : 'none',
    `--cpus=${config.pyrunCpus}`,
    `--memory=${config.pyrunMemory}`,
    `--pids-limit=${config.pyrunPids}`,
    '--user',
    config.pyrunUser,
    '-e',
    'MPLBACKEND=Agg',
    '-e',
    'PYTHONUNBUFFERED=1',
    '-e',
    'PYRUN_OUTDIR=/pyout',
    // Project source READ-ONLY; figures/ is writable for durable project figures.
    // The run scratch is mounted at a TOP-LEVEL path (not nested under the
    // read-only /workspace) — a writable mount two levels deep inside a :ro mount
    // fails to start the container on some runtimes (e.g. OrbStack).
    '-v',
    `${projHost}:/workspace:ro`,
    '-v',
    `${join(projHost, 'figures')}:/workspace/figures:rw`,
    '-v',
    `${join(projHost, '.pyout', runId)}:/pyout:rw`,
    '-w',
    '/workspace',
    config.pyrunImage,
    'sh',
    '-lc',
    inner,
  ];
  return { command: 'docker', argv, killGroup: false, containerName };
}

/** Quote an argument for a POSIX `sh -lc` command line. */
function shellQuote(arg: string): string {
  return /^[A-Za-z0-9_./:=-]+$/.test(arg) ? arg : `'${arg.replace(/'/g, `'\\''`)}'`;
}
